/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

/**
 *
 * @author Prov
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuconsultas = new javax.swing.JMenu();
        jMenuItemGaleria = new javax.swing.JMenuItem();
        jMenuItemIngresos = new javax.swing.JMenuItem();
        jMenuItemPorcentajehab = new javax.swing.JMenuItem();
        jMenuItemtotalhabitaciones = new javax.swing.JMenuItem();
        jMenuItemporcentajeOcupacion = new javax.swing.JMenuItem();
        jMenuItemcostoHab = new javax.swing.JMenuItem();
        jMenuItemBusquedaHuesped = new javax.swing.JMenuItem();
        jMenuItemHabitacionesDisp = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuconsultas.setText("Consultas");

        jMenuItemGaleria.setText("Galería de fotos");
        jMenuItemGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGaleriaActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemGaleria);

        jMenuItemIngresos.setText("Ingresos del hotel");
        jMenuconsultas.add(jMenuItemIngresos);

        jMenuItemPorcentajehab.setText("Porcentaje de ocupación por tipo de habitación");
        jMenuItemPorcentajehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPorcentajehabActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemPorcentajehab);

        jMenuItemtotalhabitaciones.setText("Total de habitaciones del hotel");
        jMenuconsultas.add(jMenuItemtotalhabitaciones);

        jMenuItemporcentajeOcupacion.setText("Porcentaje de ocupación del hotel");
        jMenuItemporcentajeOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemporcentajeOcupacionActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemporcentajeOcupacion);

        jMenuItemcostoHab.setText("Costos de habitadiones");
        jMenuconsultas.add(jMenuItemcostoHab);

        jMenuItemBusquedaHuesped.setText("Búsqueda de huésped");
        jMenuconsultas.add(jMenuItemBusquedaHuesped);

        jMenuItemHabitacionesDisp.setText("Habitaciones disponibles");
        jMenuconsultas.add(jMenuItemHabitacionesDisp);

        jMenuBar1.add(jMenuconsultas);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemsalir.setText("Salir de consultas");
        jMenuItemsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemsalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGaleriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGaleriaActionPerformed

    private void jMenuItemporcentajeOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemporcentajeOcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemporcentajeOcupacionActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemPorcentajehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPorcentajehabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPorcentajehabActionPerformed

    private void jMenuItemsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBusquedaHuesped;
    private javax.swing.JMenuItem jMenuItemGaleria;
    private javax.swing.JMenuItem jMenuItemHabitacionesDisp;
    private javax.swing.JMenuItem jMenuItemIngresos;
    private javax.swing.JMenuItem jMenuItemPorcentajehab;
    private javax.swing.JMenuItem jMenuItemcostoHab;
    private javax.swing.JMenuItem jMenuItemporcentajeOcupacion;
    private javax.swing.JMenuItem jMenuItemsalir;
    private javax.swing.JMenuItem jMenuItemtotalhabitaciones;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuconsultas;
    // End of variables declaration//GEN-END:variables
}
