/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author fer_o
 */
public class Registro extends javax.swing.JFrame {
    private MySqlConn conn=new MySqlConn();
    
   Connection con=conn.conn;
   int dispo[]=new int[15];
   int extra;
    /**
     * Creates new form Registro
     */
    public Registro() {
       
        initComponents();
         this.jLabelHbitacion.setVisible(false);
        this.jTextFieldHabitacion.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisponibilidad = new javax.swing.JPanel();
        jPanelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNopmbre = new javax.swing.JTextField();
        jTextFieldTipoHab = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldPersonaspH = new javax.swing.JTextField();
        jTextFieldDias = new javax.swing.JTextField();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jButtonDisponibilidad = new javax.swing.JButton();
        jLabelHbitacion = new javax.swing.JLabel();
        jTextFieldHabitacion = new javax.swing.JTextField();
        jButtonReservar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelDisponibilidadLayout = new javax.swing.GroupLayout(jPanelDisponibilidad);
        jPanelDisponibilidad.setLayout(jPanelDisponibilidadLayout);
        jPanelDisponibilidadLayout.setHorizontalGroup(
            jPanelDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanelDisponibilidadLayout.setVerticalGroup(
            jPanelDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jPanelDatos.setBackground(new java.awt.Color(204, 204, 204));
        jPanelDatos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("DATOS");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de habitacion:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ciudad:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Personas por habitacion");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dias a hospedarse");

        jTextFieldNopmbre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNopmbre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNopmbre.setText(" ");

        jTextFieldTipoHab.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTipoHab.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTipoHab.setText(" ");

        jTextFieldCiudad.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCiudad.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCiudad.setText(" ");

        jTextFieldPersonaspH.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPersonaspH.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPersonaspH.setText(" ");

        jTextFieldDias.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDias.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDias.setText(" ");

        jDateChooserFecha.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserFecha.setDateFormatString("yyyy/MM/dd");

        jButtonDisponibilidad.setText("Disponibilidad");
        jButtonDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisponibilidadActionPerformed(evt);
            }
        });

        jLabelHbitacion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHbitacion.setText("Habitacion:");

        jTextFieldHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHabitacion.setText(" ");

        jButtonReservar.setText("Reservar");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jButtonDisponibilidad)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jLabelHbitacion))
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldPersonaspH, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDias, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jTextFieldHabitacion)))
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jButtonReservar))))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNopmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addGap(65, 65, 65))
        );

        jPanelDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        jPanelDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldCiudad, jTextFieldDias, jTextFieldNopmbre, jTextFieldPersonaspH, jTextFieldTipoHab});

        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNopmbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTextFieldPersonaspH))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHbitacion)
                    .addComponent(jTextFieldHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDisponibilidad)
                    .addComponent(jButtonReservar))
                .addGap(72, 72, 72))
        );

        jPanelDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldDias, jTextFieldPersonaspH});

        jPanelDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldCiudad, jTextFieldNopmbre, jTextFieldTipoHab});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDisponibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDisponibilidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisponibilidadActionPerformed
        boolean band=true,band2=true;
        // TODO add your handling code here:
        //esto es hola mundo
        //eso ws mas
             
            
            int dias2=0, personas2=0, tipo=0;
            String nombre = this.jTextFieldNopmbre.getText().trim();
            String th = this.jTextFieldTipoHab.getText().trim();
            String ciudad = this.jTextFieldCiudad.getText().trim();
            String personas = this.jTextFieldPersonaspH.getText().trim();
            String dias = this.jTextFieldDias.getText().trim();
            String aux = ((JTextField) jDateChooserFecha.getDateEditor().getUiComponent()).getText();
           
            if(nombre.isEmpty()){
                band=false;
                JOptionPane.showMessageDialog(null, "Ingrese el nombre de la persona");
            }
            if(ciudad.isEmpty()){
                band=false;
                JOptionPane.showMessageDialog(null, "Ingrese el nombre de la ciudad");
            }
            if(aux.isEmpty()){
               band=false; 
               JOptionPane.showMessageDialog(null, "Ingrese la fecha de llegada");
            }
            if(dias.isEmpty()){
                band=false;
                JOptionPane.showMessageDialog(null, "Ingrese los dias a hospedarse ");
            }
            if(personas.isEmpty()){
                band=false;
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad e personas a hospedarse");
            }
            if(th.isEmpty()){
                band=false;
                JOptionPane.showMessageDialog(null, "Ingrese el tipo de habitacion deseada");
            }
            if(band==true){
              
                dias2 = Integer.parseInt(dias);
               personas2 = Integer.parseInt(personas);
               tipo = Integer.parseInt(th);
            }
            
            switch (tipo) {
                case 1: {
                    if(personas2==1){
                        band=true;
                    }else{
                        if(personas2>1 && personas2<4){
                            this.extra=(personas2-1);
                        }else{
                            band=false;
                        }
                    }                    
                    break;
                }
                case 2: {
                    if(personas2==2 || personas2==1){
                        band=true;
                    }else{
                        if(personas2>3 && personas2<5){
                            this.extra=(personas2-2);
                        }else{
                            band=false;
                        }
                    } 
                    break;
                }
                case 3: {
                    if(personas2==3 || personas2==2 || personas2==1){
                        band=true;
                    }else{
                        if(personas2>3 && personas2<6){
                            this.extra=(personas2-3);
                        }else{
                            band=false;
                        }
                    } 
                    break;
                }
                default: {
                    band=false;
                    JOptionPane.showMessageDialog(null, "Tipo de habitacion no valido");
                    break;
                }
            }
        if(!band==false){
           /* Calendar z=this.jDateChooserFecha.getCalendar();
            Calendar nueva=this.dispofecha(z,dias2 );
            Huesped x=new Huesped();
            x.setCiudadOrigen(ciudad);
            x.setEstancia(dias2);
            x.setIngreso(z);
            x.setSalida(nueva);
            x.setNombre(nombre);
            x.setPersonas(personas2);
            x.setTipohab(tipo);*/
            this.habitacionesdisp(tipo);
            
            //new Disponibilidad().setVisible(true);
           
            this.jTextFieldCiudad.disable();
            this.jTextFieldDias.disable();
            this.jTextFieldNopmbre.disable();
            this.jTextFieldPersonaspH.disable();
            this.jTextFieldTipoHab.disable();
            this.jTextFieldHabitacion.setVisible(true);
            this.jLabelHbitacion.setVisible(true);
            
           
            
        }else{
            this.jTextFieldPersonaspH.setText("");
            if(band2==false){
                this.jTextFieldTipoHab.setText("");
            }
        }
        

        
        //this.jPanelDatos.setVisible(false);
        //this.jPanelDisponibilidad.setVisible(true);
    }//GEN-LAST:event_jButtonDisponibilidadActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        // TODO add your handling code here:
            String nombre = this.jTextFieldNopmbre.getText().trim();
            String th = this.jTextFieldTipoHab.getText().trim();
            String ciudad = this.jTextFieldCiudad.getText().trim();
            String personas = this.jTextFieldPersonaspH.getText().trim();
            String dias = this.jTextFieldDias.getText().trim();
            String aux = ((JTextField) jDateChooserFecha.getDateEditor().getUiComponent()).getText();
           
            
             int  dias2 = Integer.parseInt(dias);
             int  personas2 = Integer.parseInt(personas);
              int tipo = Integer.parseInt(th);
            
            Calendar z=this.jDateChooserFecha.getCalendar();
            Calendar nueva=this.dispofecha(z,dias2 );
            Huesped x=new Huesped();
            x.setCiudadOrigen(ciudad);
            x.setEstancia(dias2);
            x.setIngreso(z);
            x.setSalida(nueva);
            x.setNombre(nombre);
            x.setPersonas(personas2);
            x.setTipohab(tipo);
            
            String hab=this.jTextFieldHabitacion.getText().trim();
            int nhab=Integer.parseInt(hab);
            if(this.correcto(x, nhab)){
                System.out.println("ojkey");
            }else{
                System.out.println("mal");
            }
            
    }//GEN-LAST:event_jButtonReservarActionPerformed

    /**
     * @param fecha
     * @param args the command line arguments
     */
    public Calendar dispofecha(Calendar fecha,int dias){
        fecha.add(Calendar.DATE, dias);
        return fecha;
    }
    public void habitacionesdisp(int th){
         ArrayList <Huesped> lista = new ArrayList();
        String query="select * from huespedes where tipohab ='"+th+"'";
        this.conn.Consult(query);
        int n=0;
        try{
        this.conn.rs.last();
        n=this.conn.rs.getRow();
        this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n "+n);
            
            int datos[]=new int [3];
            String nombre="";
            for (int i = 0; i < n; i++) {
                try{
               Huesped x=new Huesped();
               datos[0]=this.conn.rs.getInt(2);
               datos[1]=this.conn.rs.getInt(8);
               datos[2]=this.conn.rs.getInt(7);
               nombre=this.conn.rs.getString(1);
               x.setTipohab(datos[0]);
               x.setNumhab(datos[1]);
               x.setPiso(datos[2]);
               lista.add(x);
                this.conn.rs.next();
                }catch(Exception e){
                    System.out.println("Error#2 ..."+ e.getMessage());
            }
        }
            
            //int dispo[]=new int[15];
            for (int i = 0; i < lista.size(); i++) {
                dispo[i]=lista.get(i).getNumhab();
            }
            new Disponibilidad(dispo).setVisible(true);
            //String columnas[]={"Habitacion","Paciente","Diagnostico"};
           // jTableConsulta2.setModel(new DefaultTableModel(datos,columnas));
           
        }else{
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
            
    }
    public boolean correcto(Huesped x,int hab){
        
        boolean res=true,band2=true;
        if((hab<=100 || hab>115)){
            
            return false;
            
        }else{
            if(hab>115 && hab<=200){
                
                return false;
                
            }else{
                if(hab>215){
                    
                    return false;
                }
            }
        }
        for (int i = 0; i < 15; i++) {
            if (hab == this.dispo[i]) {

                String dia = String.valueOf(x.salida.get(Calendar.DATE)) ;
                String mes = String.valueOf(x.salida.get(Calendar.MONTH) + 1) + "/"; //'2021/06/09
                String año = String.valueOf(x.salida.get(Calendar.YEAR))+"/";
                String union = año + mes + dia;//17/02/21
                System.out.println(union);
                String aux = ((JTextField) jDateChooserFecha.getDateEditor().getUiComponent()).getText();
                System.out.println(aux);
                String actual="UPDATE huespedes SET nombre='" + x.getNombre() + "',"
                            + "ciudad='" + x.getCiudadOrigen() + "',ingreso='" + aux + "',personas='" + x.getPersonas()
                            + "',estancia='" + x.getEstancia()
                            + "',extra='" + (this.extra * 200) + "' WHERE numhab='" + hab + "'";
                System.out.println(actual);
                //AQUI VA EL RECIBO
                try {
                    PreparedStatement pps = this.con.prepareStatement(actual);
                    pps.executeUpdate();
                } catch (SQLException ex) {
                    System.out.println("no jalo");
                }
            }
            band2 = false;
        }
        if (band2 == false) {
            return false;
        }

      return res;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDisponibilidad;
    private javax.swing.JButton jButtonReservar;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelHbitacion;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDisponibilidad;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldHabitacion;
    private javax.swing.JTextField jTextFieldNopmbre;
    private javax.swing.JTextField jTextFieldPersonaspH;
    private javax.swing.JTextField jTextFieldTipoHab;
    // End of variables declaration//GEN-END:variables
}
