/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.List;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Prov
 */
public class Consultas extends javax.swing.JFrame {
private MySqlConn conn=new MySqlConn();
    Connection con=conn.conn;
    /**
     * Creates new form Consultas
     */
    public Consultas() {
        
        initComponents();
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);       
        this.jPanelGaleria.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelExtra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelIngresos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelPorPiso = new javax.swing.JPanel();
        jRadioPiso1 = new javax.swing.JRadioButton();
        jRadioPiso2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanelPorcentajeHab = new javax.swing.JPanel();
        jPanelTotalHab = new javax.swing.JPanel();
        jPanelPorcentajeOcup = new javax.swing.JPanel();
        jPanelCircular = new javax.swing.JPanel();
        jPanelCostoHab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanelBusquedaHuesped = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanelhabitacionesListaHuesped = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaordenanombre = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanelGaleria = new javax.swing.JPanel();
        jPanelPorHabitacion = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanelExtra = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEstancia = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuconsultas = new javax.swing.JMenu();
        jMenuItemGaleria = new javax.swing.JMenuItem();
        jMenuItemIngresos = new javax.swing.JMenuItem();
        jMenuItemPorcentajehab = new javax.swing.JMenuItem();
        jMenuItemtotalhabitaciones = new javax.swing.JMenuItem();
        jMenuItemporcentajeOcupacion = new javax.swing.JMenuItem();
        jMenuItemcostoHab = new javax.swing.JMenuItem();
        jMenuItemBusquedaHuesped = new javax.swing.JMenuItem();
        jMenuItemPorHabitacion = new javax.swing.JMenuItem();
        jMenuItemPorPiso = new javax.swing.JMenuItem();
        jMenuItemListaHuesped = new javax.swing.JMenuItem();
        jMenuItemExtra = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jLabel18.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 509, Short.MAX_VALUE)
        );

        jPanelIngresos.setBackground(new java.awt.Color(153, 204, 255));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel15.setText("Ingresos totales del hotel");

        jTextField1.setText(" ");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIngresosLayout = new javax.swing.GroupLayout(jPanelIngresos);
        jPanelIngresos.setLayout(jPanelIngresosLayout);
        jPanelIngresosLayout.setHorizontalGroup(
            jPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosLayout.createSequentialGroup()
                .addGroup(jPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIngresosLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel15))
                    .addGroup(jPanelIngresosLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIngresosLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton1)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanelIngresosLayout.setVerticalGroup(
            jPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel15)
                .addGap(57, 57, 57)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jPanelPorPiso.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup1.add(jRadioPiso1);
        jRadioPiso1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioPiso1.setText("Piso 1");
        jRadioPiso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPiso1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioPiso2);
        jRadioPiso2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRadioPiso2.setText("Piso 2");
        jRadioPiso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPiso2ActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 2, 24)); // NOI18N
        jLabel10.setText("Habitaciones Disponibles");

        jButton9.setText("Regresar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPorPisoLayout = new javax.swing.GroupLayout(jPanelPorPiso);
        jPanelPorPiso.setLayout(jPanelPorPisoLayout);
        jPanelPorPisoLayout.setHorizontalGroup(
            jPanelPorPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPorPisoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(61, 61, 61))
            .addGroup(jPanelPorPisoLayout.createSequentialGroup()
                .addGroup(jPanelPorPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPorPisoLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(jPanelPorPisoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioPiso1)
                .addGap(97, 97, 97)
                .addComponent(jRadioPiso2)
                .addGap(223, 223, 223))
        );
        jPanelPorPisoLayout.setVerticalGroup(
            jPanelPorPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorPisoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelPorPisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioPiso2)
                    .addComponent(jRadioPiso1))
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanelPorcentajeHabLayout = new javax.swing.GroupLayout(jPanelPorcentajeHab);
        jPanelPorcentajeHab.setLayout(jPanelPorcentajeHabLayout);
        jPanelPorcentajeHabLayout.setHorizontalGroup(
            jPanelPorcentajeHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanelPorcentajeHabLayout.setVerticalGroup(
            jPanelPorcentajeHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTotalHabLayout = new javax.swing.GroupLayout(jPanelTotalHab);
        jPanelTotalHab.setLayout(jPanelTotalHabLayout);
        jPanelTotalHabLayout.setHorizontalGroup(
            jPanelTotalHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanelTotalHabLayout.setVerticalGroup(
            jPanelTotalHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCircularLayout = new javax.swing.GroupLayout(jPanelCircular);
        jPanelCircular.setLayout(jPanelCircularLayout);
        jPanelCircularLayout.setHorizontalGroup(
            jPanelCircularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanelCircularLayout.setVerticalGroup(
            jPanelCircularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelPorcentajeOcupLayout = new javax.swing.GroupLayout(jPanelPorcentajeOcup);
        jPanelPorcentajeOcup.setLayout(jPanelPorcentajeOcupLayout);
        jPanelPorcentajeOcupLayout.setHorizontalGroup(
            jPanelPorcentajeOcupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorcentajeOcupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCircular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPorcentajeOcupLayout.setVerticalGroup(
            jPanelPorcentajeOcupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorcentajeOcupLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanelCircular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jPanelCostoHab.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        jLabel1.setText("Habitación");

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel2.setText("Sencilla");

        jLabel3.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        jLabel3.setText("Precio");

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel4.setText("Doble");

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel5.setText("Triple");

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel6.setText("$2000");

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel7.setText("$4000");

        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel8.setText("$6000");

        jLabel9.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel9.setText("Costos");

        jButton8.setText("Regresar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCostoHabLayout = new javax.swing.GroupLayout(jPanelCostoHab);
        jPanelCostoHab.setLayout(jPanelCostoHabLayout);
        jPanelCostoHabLayout.setHorizontalGroup(
            jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCostoHabLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87))
                    .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                        .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addContainerGap())))
            .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCostoHabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanelCostoHabLayout.setVerticalGroup(
            jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGroup(jPanelCostoHabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel5))
                    .addGroup(jPanelCostoHabLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(91, 91, 91))
        );

        jPanelCostoHabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        jPanelBusquedaHuesped.setBackground(new java.awt.Color(255, 204, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Nombre del huesped:");

        jTextField2.setText(" ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Búsqueda por nombre");

        javax.swing.GroupLayout jPanelBusquedaHuespedLayout = new javax.swing.GroupLayout(jPanelBusquedaHuesped);
        jPanelBusquedaHuesped.setLayout(jPanelBusquedaHuespedLayout);
        jPanelBusquedaHuespedLayout.setHorizontalGroup(
            jPanelBusquedaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaHuespedLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaHuespedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBusquedaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaHuespedLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaHuespedLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaHuespedLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(45, 45, 45))))
        );
        jPanelBusquedaHuespedLayout.setVerticalGroup(
            jPanelBusquedaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaHuespedLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel14)
                .addGap(54, 54, 54)
                .addGroup(jPanelBusquedaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addGap(48, 48, 48))
        );

        jPanelhabitacionesListaHuesped.setBackground(new java.awt.Color(204, 255, 204));

        jTextAreaordenanombre.setColumns(20);
        jTextAreaordenanombre.setRows(5);
        jScrollPane2.setViewportView(jTextAreaordenanombre);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setText("Ordenado por Nombre Ascendentemente");

        jButton7.setText("Regresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelhabitacionesListaHuespedLayout = new javax.swing.GroupLayout(jPanelhabitacionesListaHuesped);
        jPanelhabitacionesListaHuesped.setLayout(jPanelhabitacionesListaHuespedLayout);
        jPanelhabitacionesListaHuespedLayout.setHorizontalGroup(
            jPanelhabitacionesListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelhabitacionesListaHuespedLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanelhabitacionesListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelhabitacionesListaHuespedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(300, 300, 300))
        );
        jPanelhabitacionesListaHuespedLayout.setVerticalGroup(
            jPanelhabitacionesListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelhabitacionesListaHuespedLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton7)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanelGaleriaLayout = new javax.swing.GroupLayout(jPanelGaleria);
        jPanelGaleria.setLayout(jPanelGaleriaLayout);
        jPanelGaleriaLayout.setHorizontalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanelGaleriaLayout.setVerticalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jPanelPorHabitacion.setBackground(new java.awt.Color(255, 255, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Consulta por habitación");

        jLabel17.setText("Selecciona una habitación: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215" }));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPorHabitacionLayout = new javax.swing.GroupLayout(jPanelPorHabitacion);
        jPanelPorHabitacion.setLayout(jPanelPorHabitacionLayout);
        jPanelPorHabitacionLayout.setHorizontalGroup(
            jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorHabitacionLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPorHabitacionLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPorHabitacionLayout.createSequentialGroup()
                        .addGroup(jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelPorHabitacionLayout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4))))
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPorHabitacionLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(67, 67, 67))))
        );
        jPanelPorHabitacionLayout.setVerticalGroup(
            jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorHabitacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addGroup(jPanelPorHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jButton4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton5)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanelExtra.setBackground(new java.awt.Color(153, 255, 255));

        jTextAreaEstancia.setColumns(20);
        jTextAreaEstancia.setRows(5);
        jScrollPane3.setViewportView(jTextAreaEstancia);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setText("Orden por estancia mayor a menor");

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelExtraLayout = new javax.swing.GroupLayout(jPanelExtra);
        jPanelExtra.setLayout(jPanelExtraLayout);
        jPanelExtraLayout.setHorizontalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExtraLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExtraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(181, 181, 181))
        );
        jPanelExtraLayout.setVerticalGroup(
            jPanelExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExtraLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(60, 60, 60))
        );

        jMenuconsultas.setText("Consultas");

        jMenuItemGaleria.setText("Galería de fotos");
        jMenuItemGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGaleriaActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemGaleria);

        jMenuItemIngresos.setText("Ingresos del hotel");
        jMenuItemIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresosActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemIngresos);

        jMenuItemPorcentajehab.setText("Porcentaje de ocupación por tipo de habitación");
        jMenuItemPorcentajehab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPorcentajehabActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemPorcentajehab);

        jMenuItemtotalhabitaciones.setText("Total de habitaciones del hotel");
        jMenuItemtotalhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemtotalhabitacionesActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemtotalhabitaciones);

        jMenuItemporcentajeOcupacion.setText("Porcentaje de ocupación del hotel");
        jMenuItemporcentajeOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemporcentajeOcupacionActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemporcentajeOcupacion);

        jMenuItemcostoHab.setText("Costos de habitadiones");
        jMenuItemcostoHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcostoHabActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemcostoHab);

        jMenuItemBusquedaHuesped.setText("Búsqueda de huésped");
        jMenuItemBusquedaHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBusquedaHuespedActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemBusquedaHuesped);

        jMenuItemPorHabitacion.setText("Busqueda por habitación");
        jMenuItemPorHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPorHabitacionActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemPorHabitacion);

        jMenuItemPorPiso.setText("Busqueda por piso");
        jMenuItemPorPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPorPisoActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemPorPiso);

        jMenuItemListaHuesped.setText("Lista de Huéspedes por orden");
        jMenuItemListaHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaHuespedActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemListaHuesped);

        jMenuItemExtra.setText("Lista de huéspedes por estancia");
        jMenuItemExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtraActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemExtra);

        jMenuBar1.add(jMenuconsultas);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jMenuItemsalir.setText("Salir de consultas");
        jMenuItemsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemsalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCostoHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorcentajeHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelTotalHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorcentajeOcup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelBusquedaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelhabitacionesListaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorPiso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelGaleria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCostoHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorcentajeHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanelTotalHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorcentajeOcup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanelBusquedaHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelhabitacionesListaHuesped, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPorPiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelExtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelGaleria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItemsalirActionPerformed

    private void jMenuItemPorPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPorPisoActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);       
        this.jPanelGaleria.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelPorPiso.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemPorPisoActionPerformed

    private void jMenuItemPorHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPorHabitacionActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
       this.jPanelPorPiso.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(true);

    }//GEN-LAST:event_jMenuItemPorHabitacionActionPerformed

    private void jMenuItemListaHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaHuespedActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(true);
        
        ArrayList <nHues> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
       
        this.conn.Consult(query);
         
        int n=0;
        try{
        System.out.println("hola");
        this.conn.rs.last();
        n=this.conn.rs.getRow();
        this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n "+n);
            //DefaultComboBoxModel modelo= new DefaultComboBoxModel();
            int datos[]=new int [3];
           String datos2[]=new String[10];
            for (int i = 0; i < n; i++) {//n cantidad de registros que coinciden
                try{
               nHues x=new nHues();
               datos2[0]=this.conn.rs.getString(1);//nombre
               datos[0]=this.conn.rs.getInt(8);//numero
                    
               //datos[2]=this.conn.rs.getInt(7);
               //nombre=this.conn.rs.getString(1);
               x.setNombre(datos2[0]);
               x.setNumhab(datos[0]);
              lista.add(x);
                    
                //modelo.addElement(x.getNumhab());
                this.conn.rs.next();
                }catch(Exception e){
                    System.out.println("Error#2 ..."+ e.getMessage());
            }
        }  
           Collections.sort(lista);
        this.jTextAreaordenanombre.setText(lista.toString());     
        }      
    }//GEN-LAST:event_jMenuItemListaHuespedActionPerformed

    private void jMenuItemBusquedaHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBusquedaHuespedActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(true);
    }//GEN-LAST:event_jMenuItemBusquedaHuespedActionPerformed

    private void jMenuItemcostoHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcostoHabActionPerformed
        // TODO add your handling code here:

        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelCostoHab.setVisible(true);
    }//GEN-LAST:event_jMenuItemcostoHabActionPerformed

    private void jMenuItemporcentajeOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemporcentajeOcupacionActionPerformed
        // TODO add your handling code here:
        this.jPanelTotalHab.setVisible(false);
        this.jPanelCostoHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(true);
        ArrayList<Huesped> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n " + n);
            for (int i = 0; i < n; i++) {
                try {
                    Huesped x=new Huesped();
                    //x.setNumhab(this.conn.rs.getInt(8));
                    x.setTipohab(this.conn.rs.getInt(2));
                    lista.add(x);
                    
                   
                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error#2 ..." + e.getMessage());
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
        int cont1=0,cont2=0,cont3=0;
        for (int i = 0; i < lista.size(); i++) {
            switch(lista.get(i).getTipohab()){
                case 1:{
                   cont1++;
                   break;
                }
                
                case 2:
                {
                    cont2++;
                    break;
                }
                
                case 3:{
                    cont3++;
                    break;
                }
                
            }
        }
        
        
        DefaultPieDataset datos = new DefaultPieDataset();
        int a=((cont1++)+(cont2++)+(cont3++));
        datos.setValue("Ocupado", a);
        datos.setValue("Disponible", (30-a));
        //datos.setValue("Habitacion Triples", cont3++);
        JFreeChart grafico_circular=ChartFactory.createPieChart("Total de habitaciones"
        , datos, true, true,false);
        ChartPanel panel =new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(350,327));        
        jPanelPorcentajeOcup.setLayout(new BorderLayout());
        jPanelPorcentajeOcup.add(panel,BorderLayout.CENTER);       
        pack();
        repaint();

    }//GEN-LAST:event_jMenuItemporcentajeOcupacionActionPerformed

    private void jMenuItemtotalhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemtotalhabitacionesActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelTotalHab.setVisible(true);
         ArrayList<Huesped> lista = new ArrayList();
        String query = "select * from huespedes";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n " + n);
            for (int i = 0; i < n; i++) {
                try {
                    Huesped x=new Huesped();
                    //x.setNumhab(this.conn.rs.getInt(8));
                    x.setTipohab(this.conn.rs.getInt(2));
                    lista.add(x);
                    
                   
                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error#2 ..." + e.getMessage());
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
        int cont1=0,cont2=0,cont3=0;
        for (int i = 0; i < lista.size(); i++) {
            switch(lista.get(i).getTipohab()){
                case 1:{
                   cont1++;
                   break;
                }
                
                case 2:
                {
                    cont2++;
                    break;
                }
                
                case 3:{
                    cont3++;
                    break;
                }
                
            }
        }
        
        
        DefaultPieDataset datos = new DefaultPieDataset();
        
        datos.setValue("Habitacion Secncillas", cont1++);
        datos.setValue("Habitacion Dobles", cont2++);
        datos.setValue("Habitacion Triples", cont3++);
        JFreeChart grafico_circular=ChartFactory.createPieChart("Total de habitaciones"
        , datos, true, true,false);
        ChartPanel panel =new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(350,327));        
        jPanelTotalHab.setLayout(new BorderLayout());
        jPanelTotalHab.add(panel,BorderLayout.CENTER);       
        pack();
        repaint();
    }//GEN-LAST:event_jMenuItemtotalhabitacionesActionPerformed

    private void jMenuItemPorcentajehabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPorcentajehabActionPerformed
        // TODO add your handling code here:
        this.jPanelCostoHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelIngresos.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(true);
         ArrayList<Huesped> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
        this.conn.Consult(query);
        int n = 0,ganancias=0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n " + n);

        
            for (int i = 0; i < n; i++) {
                try {
                    Huesped x=new Huesped();
                    x.setNumhab(this.conn.rs.getInt(8));
                    x.setTipohab(this.conn.rs.getInt(2));
                    lista.add(x);
                    
                   
                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error#2 ..." + e.getMessage());
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
        int cont1=0,cont2=0,cont3=0;
        for (int i = 0; i < lista.size(); i++) {
            switch(lista.get(i).getTipohab()){
                case 1:{
                   cont1++;
                   break;
                }
                
                case 2:
                {
                    cont2++;
                    break;
                }
                
                case 3:{
                    cont3++;
                    break;
                }
                
            }
        }
        
        
        DefaultPieDataset datos = new DefaultPieDataset();
        
        datos.setValue("Habitacion Tipo1", cont1++);
        datos.setValue("Habitacion Tipo2", cont2++);
        datos.setValue("Habitacion Tipo3", cont3++);
        JFreeChart grafico_circular=ChartFactory.createPieChart("Porcentaje de ocupacion"
        , datos, true, true,false);
        ChartPanel panel =new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(350,327));        
        jPanelPorcentajeHab.setLayout(new BorderLayout());
        jPanelPorcentajeHab.add(panel,BorderLayout.CENTER);       
        pack();
        repaint();
    }//GEN-LAST:event_jMenuItemPorcentajehabActionPerformed

    private void jMenuItemIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresosActionPerformed
        // TODO add your handling code here:
        this.jPanelTotalHab.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelIngresos.setVisible(true);
        this.jTextField1.enable(false);
        String query = "select * from ganancias ";
        this.conn.Consult(query);
        int n = 0,ganancias=0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n " + n);

        
            for (int i = 0; i < n; i++) {
                try {
                    ganancias=ganancias+this.conn.rs.getInt(1);
                   
                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error#2 ..." + e.getMessage());
                }
            }
            this.jTextField1.setText(String.valueOf(ganancias));
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
        
    }//GEN-LAST:event_jMenuItemIngresosActionPerformed

    private void jMenuItemGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGaleriaActionPerformed
        // TODO add your handling code here:
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorPiso.setVisible(false);
        this.jPanelExtra.setVisible(false);
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(true);
        new Galeria().setVisible(true);
        
        

    }//GEN-LAST:event_jMenuItemGaleriaActionPerformed

    private void jRadioPiso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPiso1ActionPerformed
        // TODO add your handling code here:
        this.jTextArea.setText("");
        habitacionesdisp(1);
       
    }//GEN-LAST:event_jRadioPiso1ActionPerformed
public void habitacionesdisp(int th){
         ArrayList <Huesped> lista = new ArrayList();
        String query="select * from huespedes where piso ='"+th+"' && nombre IS NULL";
        this.conn.Consult(query);
        int n=0;
        try{
        this.conn.rs.last();
        n=this.conn.rs.getRow();
        this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n "+n);
            //DefaultComboBoxModel modelo= new DefaultComboBoxModel();
            int datos[]=new int [3];
           
            for (int i = 0; i < n; i++) {//n cantidad de registros que coinciden
                try{
               Huesped x=new Huesped();
               datos[0]=this.conn.rs.getInt(2);//tipo
               datos[1]=this.conn.rs.getInt(8);//numero
               //datos[2]=this.conn.rs.getInt(7);
               //nombre=this.conn.rs.getString(1);
               x.setTipohab(datos[0]);
               x.setNumhab(datos[1]);
               //x.setPiso(datos[2]);
               lista.add(x);
                //modelo.addElement(x.getNumhab());
                this.conn.rs.next();
                }catch(Exception e){
                    System.out.println("Error#2 ..."+ e.getMessage());
            }
        }  
        int a[]=new int[30],b[] = new int [30];
            
            for (int i = 0; i < lista.size(); i++) {
                a[i]=lista.get(i).getNumhab();
                b[i]=lista.get(i).getTipohab();
                //this.jTextArea.setText("Numero de la habitación: "+a+" tipo de la habitación: "+b+"\n");
            }
            for (int i = 0; i < lista.size(); i++) {
               
                this.jTextArea.append("# Habitacion: "+a[i]+" Tipo: "+b[i]+"\n");
            }
        }
}
    private void jRadioPiso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPiso2ActionPerformed
        // TODO add your handling code here:
        this.jTextArea.setText("");
        habitacionesdisp(2);
    }//GEN-LAST:event_jRadioPiso2ActionPerformed

    private void jMenuItemExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExtraActionPerformed
        // TODO add your handling code here:
        this.jPanelIngresos.setVisible(false);
        this.jPanelPorPiso.setVisible(false);      
        this.jPanelPorcentajeHab.setVisible(false);
        this.jPanelTotalHab.setVisible(false);
        this.jPanelPorcentajeOcup.setVisible(false);
        this.jPanelCostoHab.setVisible(false);
        this.jPanelBusquedaHuesped.setVisible(false);
        this.jPanelhabitacionesListaHuesped.setVisible(false);
        this.jPanelPorHabitacion.setVisible(false);
        this.jPanelGaleria.setVisible(false);
        this.jPanelExtra.setVisible(true);
        ArrayList <nEst> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
       
        this.conn.Consult(query);
         
        int n=0;
        try{
        System.out.println("hola");
        this.conn.rs.last();
        n=this.conn.rs.getRow();
        this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n "+n);
            //DefaultComboBoxModel modelo= new DefaultComboBoxModel();
            int datos[]=new int [3];
           String datos2[]=new String[10];
            for (int i = 0; i < n; i++) {//n cantidad de registros que coinciden
                try{
               nEst x=new nEst();
               datos2[0]=this.conn.rs.getString(1);//nombre
               datos[0]=this.conn.rs.getInt(6);//estancia
               datos[1]=this.conn.rs.getInt(8);
               //datos[2]=this.conn.rs.getInt(7);
               //nombre=this.conn.rs.getString(1);
               x.setNombre(datos2[0]);
               x.setNumhab(datos[1]);
               x.setEstancia(datos[0]);
              lista.add(x);
                    
                //modelo.addElement(x.getNumhab());
                this.conn.rs.next();
                }catch(Exception e){
                    System.out.println("Error#2 ..."+ e.getMessage());
            }
        }  
        Collections.sort(lista);
        Collections.reverse(lista);
        this.jTextAreaEstancia.setText(lista.toString());     
        }    
    }//GEN-LAST:event_jMenuItemExtraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String nom=this.jTextField2.getText().trim();
        int hab=0,piso=0;
        if(nom.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un nombre de huesped");
        }else{
            this.jTextArea1.setVisible(true);
            this.jButton2.setVisible(true);
            String query = "select * from huespedes where nombre ='" + nom + "'";
            this.conn.Consult(query);
            int n = 0;
            try {
                this.conn.rs.last();
                n = this.conn.rs.getRow();
                this.conn.rs.first();
            } catch (Exception e) {
                System.out.println("Error#1 ...");
            }
            if (n != 0) {

               

                for (int i = 0; i < n; i++) {
                    try {
                        hab=this.conn.rs.getInt(8);
                        piso=this.conn.rs.getInt(7);
                  

                        this.conn.rs.next();
                    } catch (Exception e) {
                        System.out.println("Error#2 ..." + e.getMessage());
                    }
                }

               this.jTextArea1.append(nom+" Habitacion:"+hab+" Piso:"+piso);
            //int dispo[]=new int[15];

            //String columnas[]={"Habitacion","Paciente","Diagnostico"};
                // jTableConsulta2.setModel(new DefaultTableModel(datos,columnas));
            } else {
                JOptionPane.showMessageDialog(this, "No hay registro con el nombre del huesped");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jTextArea2.setText("");
        String hab=this.jComboBox1.getSelectedItem().toString();
        String nombre="";
        int hab2=Integer.valueOf(hab);
        
            
            String query = "select * from huespedes where numhab='" + hab2+ "'";
            this.conn.Consult(query);
            int n = 0;
            try {
                this.conn.rs.last();
                n = this.conn.rs.getRow();
                this.conn.rs.first();
            } catch (Exception e) {
                System.out.println("Error#1 ...");
            }
            if (n != 0) {
                for (int i = 0; i < n; i++) {
                    try {
                       nombre=this.conn.rs.getString(1);

                        this.conn.rs.next();
                    } catch (Exception e) {
                        System.out.println("Error#2 ..." + e.getMessage());
                    }
                }
                 if(nombre==null){
                      this.jTextArea2.append("Habitacion vacia");
                 }else{
                     this.jTextArea2.append("La habitacion esta ocupada por "+nombre);
                 }
               
            
            } else {
                JOptionPane.showMessageDialog(this, "No hay registro con el nombre del huesped");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBusquedaHuesped;
    private javax.swing.JMenuItem jMenuItemExtra;
    private javax.swing.JMenuItem jMenuItemGaleria;
    private javax.swing.JMenuItem jMenuItemIngresos;
    private javax.swing.JMenuItem jMenuItemListaHuesped;
    private javax.swing.JMenuItem jMenuItemPorHabitacion;
    private javax.swing.JMenuItem jMenuItemPorPiso;
    private javax.swing.JMenuItem jMenuItemPorcentajehab;
    private javax.swing.JMenuItem jMenuItemcostoHab;
    private javax.swing.JMenuItem jMenuItemporcentajeOcupacion;
    private javax.swing.JMenuItem jMenuItemsalir;
    private javax.swing.JMenuItem jMenuItemtotalhabitaciones;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuconsultas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBusquedaHuesped;
    private javax.swing.JPanel jPanelCircular;
    private javax.swing.JPanel jPanelCostoHab;
    private javax.swing.JPanel jPanelExtra;
    private javax.swing.JPanel jPanelGaleria;
    private javax.swing.JPanel jPanelIngresos;
    private javax.swing.JPanel jPanelPorHabitacion;
    private javax.swing.JPanel jPanelPorPiso;
    private javax.swing.JPanel jPanelPorcentajeHab;
    private javax.swing.JPanel jPanelPorcentajeOcup;
    private javax.swing.JPanel jPanelTotalHab;
    private javax.swing.JPanel jPanelhabitacionesListaHuesped;
    private javax.swing.JRadioButton jRadioPiso1;
    private javax.swing.JRadioButton jRadioPiso2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaEstancia;
    private javax.swing.JTextArea jTextAreaordenanombre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
