/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import misclases.MySqlConn;
import misclases.Registro;
import misclases.Salida;

/**
 *
 * @author fer_o
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private MySqlConn conn=new MySqlConn();
    
   Connection con=conn.conn;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        String p="1",tp="0";
        int nh=100;
        for (int i = 0; i < 15; i++) {
            nh++;
            if(i<6){
                tp="1";
            }
            if(i>=6 && i<=12){
                tp="2";
            }
            if(i>12){
                tp="3";
            }
            String parte1="Insert into huespedes(piso, numhab, tipohab) VALUES (";
            String parte2="'"+p+"','"+nh+"','"+tp+"')";
             String query= parte1+parte2;     
            this.conn.Update(query);
        }
        p="2";
        nh=200;
        for (int i = 0; i < 15; i++) {
            nh++;
            if(i<3){
                tp="1";
            }
            if(i>=3 && i<=6){
                tp="2";
            }
            if(i>6){
                tp="3";
            }
            String parte1="Insert into huespedes(piso, numhab, tipohab) VALUES (";
            String parte2="'"+p+"','"+nh+"','"+tp+"')";
             String query= parte1+parte2;     
            this.conn.Update(query);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCheckIN = new javax.swing.JButton();
        jButtoncheckOUT = new javax.swing.JButton();
        jButtonConsultas = new javax.swing.JButton();
        jButtonSALIR = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCheckIN.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCheckIN.setText("CHECK IN");
        jButtonCheckIN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButtonCheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckINActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCheckIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 69, 134, 45));

        jButtoncheckOUT.setBackground(new java.awt.Color(0, 102, 153));
        jButtoncheckOUT.setText("CHECK OUT");
        jButtoncheckOUT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButtoncheckOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncheckOUTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncheckOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 69, 134, 45));

        jButtonConsultas.setBackground(new java.awt.Color(0, 102, 153));
        jButtonConsultas.setText("CONSULTAS");
        jButtonConsultas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButtonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 178, 134, 45));

        jButtonSALIR.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSALIR.setText("SALIR");
        jButtonSALIR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 288, 134, 45));

        jButtonModificar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 255), 3, true));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 178, 134, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultasActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
            new Consultas().setVisible(true);
        
        
      
        
    }//GEN-LAST:event_jButtonConsultasActionPerformed

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButtonCheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckINActionPerformed
        boolean a=false;
        a=hotellleno();
        if (a==true)
            JOptionPane.showMessageDialog(this, "Hotel lleno!!");           
        else
        new Registro().setVisible(true);
        
        //dispose();
    }//GEN-LAST:event_jButtonCheckINActionPerformed

    private void jButtoncheckOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncheckOUTActionPerformed
        // TODO add your handling code here:
        new Salida().setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButtoncheckOUTActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        new Modificar().setVisible(true);
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    public boolean hotellleno(){
        ArrayList <Huesped> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n==30) 
        return true;
        else
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckIN;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JButton jButtoncheckOUT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
