/*
 * To change this license header, choose License Headers in Project Properties.  
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misclases;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import misclases.MySqlConn;

/**
 *
 * @author fer_o
 */
public class Modificar extends javax.swing.JFrame {
     private MySqlConn conn=new MySqlConn();
    Connection con=conn.conn;
    ArrayList<Huesped> lista = new ArrayList();
    int indice;
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        
        this.jButtonDiasHosp.setVisible(false);
        this.jButtonNombre.setVisible(false);
        this.jButtonPersonasPhab.setVisible(false);
        this.jButtonCiudad.setVisible(false);
       // this.jComboBox2.enable(false);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        ////
        //ArrayList<Huesped> lista = new ArrayList();
        String query = "select * from huespedes where nombre IS NOT NULL";
        this.conn.Consult(query);
        int n = 0;
        try {
            this.conn.rs.last();
            n = this.conn.rs.getRow();
            this.conn.rs.first();
        } catch (Exception e) {
            System.out.println("Error#1 ...");
        }
        if (n != 0) {
            System.out.println("n " + n);

            int datos[] = new int[5];
            String nombre = "",ciudad="";
            for (int i = 0; i < n; i++) {
                try {
                    Huesped x = new Huesped();
                    datos[0] = this.conn.rs.getInt(2);//tipohab
                    datos[1] = this.conn.rs.getInt(8);//numhab
                    datos[2] = this.conn.rs.getInt(7);//piso
                    datos[3] = this.conn.rs.getInt(5);//personasPhab
                    datos[4] = this.conn.rs.getInt(6);//estancia
                    ciudad=this.conn.rs.getString(3);//ciudad
                    nombre = this.conn.rs.getString(1);//nombre
                    x.setTipohab(datos[0]);
                    x.setNumhab(datos[1]);
                    x.setPiso(datos[2]);
                    x.setPersonas(datos[3]);
                    x.setEstancia(datos[4]);
                    x.setNombre(nombre);
                    x.setCiudadOrigen(ciudad);
                    lista.add(x);
                    modelo.addElement(x.getNumhab());
                    this.conn.rs.next();
                } catch (Exception e) {
                    System.out.println("Error#2 ..." + e.getMessage());
                }
            }
            this.jComboBoxHab.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos ...");
        }
       /* String hab=this.jComboBox1.getSelectedItem().toString();
        int  nhab= Integer.parseInt(hab);
        /*int aux;
        for (int i = 0; i < lista.size(); i++) {
            aux=lista.get(i).getNumhab();
            if(nhab==aux){
                this.jTextFieldEstancia.setText(String.valueOf(lista.get(i).getEstancia()));
                this.jTextFieldNombre.setText(lista.get(i).getNombre());
                this.jTextFieldPersonasPhab.setText(String.valueOf(lista.get(i).getPersonas()));
                this.jTextFieldPiso.setText(String.valueOf(lista.get(i).getPiso()));
                this.jTextFieldTipoHab.setText(String.valueOf(lista.get(i).getTipohab()));
                break;
            }
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxHab = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstancia = new javax.swing.JTextField();
        jButtonPersonasPhab = new javax.swing.JButton();
        jButtonDiasHosp = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jComboBoxPersonasHab = new javax.swing.JComboBox();
        jButtonNombre = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCiudad = new javax.swing.JTextField();
        jButtonCiudad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("MODIFICAR DATOS");

        jLabel2.setText("Num. Hab:");

        jLabel4.setText("Personas por Habitacion");

        jLabel5.setText("Dias a hospedarse");

        jTextFieldEstancia.setText(" ");

        jButtonPersonasPhab.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPersonasPhab.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonPersonasPhab.setText("Cambiar");
        jButtonPersonasPhab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonasPhabActionPerformed(evt);
            }
        });

        jButtonDiasHosp.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDiasHosp.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonDiasHosp.setText("Cambiar");
        jButtonDiasHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiasHospActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre de quien Reservo");

        jTextFieldNombre.setText(" ");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jComboBoxPersonasHab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxPersonasHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPersonasHabActionPerformed(evt);
            }
        });

        jButtonNombre.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNombre.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonNombre.setText("Cambiar");
        jButtonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciudad Origen");

        jTextFieldCiudad.setText(" ");

        jButtonCiudad.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCiudad.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButtonCiudad.setText("Cambiar");
        jButtonCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificar)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(152, 152, 152)
                        .addComponent(jButtonNombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(189, 189, 189)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxHab, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonDiasHosp))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jComboBoxPersonasHab, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPersonasPhab))
                                        .addComponent(jTextFieldCiudad)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCiudad)))))
                .addGap(12, 12, 12)
                .addComponent(jButtonGuardar)
                .addGap(28, 28, 28))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonNombre, jButtonPersonasPhab});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonGuardar, jButtonModificar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPersonasHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPersonasPhab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiasHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonGuardar, jButtonModificar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPersonasPhabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonasPhabActionPerformed
        // TODO add your handling code here:
       this.jComboBoxPersonasHab.enable(true);
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
       switch(lista.get(this.indice).getTipohab()){
           case 1:{
                modelo.addElement(1);
                modelo.addElement(2);
                modelo.addElement(3);
               break;}
           case 2:{
               modelo.addElement(1);
               modelo.addElement(2);
               modelo.addElement(3);
               modelo.addElement(4);
               break;}
           case 3:{
               modelo.addElement(1);
               modelo.addElement(2);
               modelo.addElement(3);
               modelo.addElement(4);
               modelo.addElement(5);
               break;}
       }      
       this.jComboBoxPersonasHab.setModel(modelo);
     
    }//GEN-LAST:event_jButtonPersonasPhabActionPerformed

    private void jButtonDiasHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiasHospActionPerformed
        // TODO add your handling code here:
        this.jTextFieldEstancia.setText("");
        this.jTextFieldEstancia.enable(true);
    }//GEN-LAST:event_jButtonDiasHospActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here
        //aqui copiar lo de anterior 
        this.jButtonCiudad.setVisible(true);
        this.jButtonDiasHosp.setVisible(true);
        this.jButtonNombre.setVisible(true);
        this.jButtonPersonasPhab.setVisible(true);
        
        String hab=this.jComboBoxHab.getSelectedItem().toString();
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        int  nhab= Integer.parseInt(hab);
        int aux,nump,tipo;
        for (int i = 0; i < lista.size(); i++) {
            aux=lista.get(i).getNumhab();
            if(nhab==aux){
                this.jTextFieldEstancia.setText(String.valueOf(lista.get(i).getEstancia()));
                this.jTextFieldNombre.setText(lista.get(i).getNombre());
                this.jTextFieldCiudad.setText(lista.get(i).getCiudadOrigen());
                nump=lista.get(i).getPersonas();
                this.indice=i;
                modelo.addElement(nump);
                this.jComboBoxPersonasHab.setModel(modelo);
                
                
                
                //this.jTextFieldPersonasPhab.setText(String.valueOf(lista.get(i).getPersonas()));
          //      this.jTextFieldPiso.setText(String.valueOf(lista.get(i).getPiso()));
                //this.jTextFieldTipoHab.setText(String.valueOf(lista.get(i).getTipohab()));
                
                break;
            }
        }
        this.jTextFieldEstancia.enable(false);
        this.jTextFieldNombre.enable(false);
       this.jComboBoxPersonasHab.enable(false);
      this.jTextFieldCiudad.enable(false);
        //this.jTextFieldPiso.enable(false);
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        String nom=this.jTextFieldNombre.getText().trim();
        String ciudad=this.jTextFieldCiudad.getText().trim();
        String dias2=this.jTextFieldEstancia.getText().trim();
        int per=this.jComboBoxPersonasHab.getSelectedIndex();
        
        per++;
        boolean band=true;
        if(ciudad.isEmpty()){
            band=false;
        }
        if(nom.isEmpty()){
            band=false;
        }
        if(dias2.isEmpty()){
            band=false;
        }
        
        if(band==true){
            int dias=Integer.valueOf(this.jTextFieldEstancia.getText().trim());
            String actual="UPDATE huespedes SET nombre='" + nom + "',"
                            + "ciudad='"+ciudad+"',personas='" + per
                            + "',estancia='" +dias
                            + "' WHERE numhab='" + lista.get(this.indice).getNumhab() + "'";
                System.out.println(actual);
                
                try {
                    PreparedStatement pps = this.con.prepareStatement(actual);
                    pps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Modificacion guardada con exito");
                } catch (SQLException ex) {
                    System.out.println("no jalo");
                }
                dispose();
        }
             
        
        
       
       
       
      
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxPersonasHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPersonasHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPersonasHabActionPerformed

    private void jButtonNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombreActionPerformed
        // TODO add your handling code here:
        this.jTextFieldNombre.setText("");
        this.jTextFieldNombre.enable(true);
    }//GEN-LAST:event_jButtonNombreActionPerformed

    private void jButtonCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCiudadActionPerformed
        // TODO add your handling code here:
        this.jTextFieldCiudad.setText("");
        this.jTextFieldCiudad.enable(true);
    }//GEN-LAST:event_jButtonCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCiudad;
    private javax.swing.JButton jButtonDiasHosp;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNombre;
    private javax.swing.JButton jButtonPersonasPhab;
    private javax.swing.JComboBox jComboBoxHab;
    private javax.swing.JComboBox jComboBoxPersonasHab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldEstancia;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
